spring.application.name=gymlog

#??????????? ?? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/gymlog
spring.datasource.username=postgres
spring.datasource.password=1234


# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true